# Generated by Django 2.2.2 on 2020-02-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_plaza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rtype', models.CharField(max_length=100)),
                ('ingredient', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('pom', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='recipe/images')),
            ],
        ),
    ]
