# Generated by Django 2.2.2 on 2020-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_plaza', '0003_auto_20200206_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_table',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe_table',
            old_name='pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='recipe_table',
            old_name='pom',
            new_name='process_of_making',
        ),
        migrations.RenameField(
            model_name='recipe_table',
            old_name='rname',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='recipe_table',
            old_name='rtype',
            new_name='recipe_type',
        ),
    ]
